#%RAML 0.8
---
title: Preferential Voting Admin Server
baseUri: http://localhost:8000

/api/voteDefs:
  displayName: Vote Definition
  get:
    description: Get list of vote definitions
    headers:
      application/json:
    responses:
      200:
  put:
    description: Updates existing vote definition
    headers:
      application/json:
    responses:
      200:
      201:
      203:
  post:
    description: Creates new vote definition
    body:
      application/json:        
    headers:
      application/json:
    responses:
      200:
      201:
      203:
      403:

  /{voteDefId}:
    description: Vote definition id
    uriParameters:
      voteDefId:
        required: true
        description: Vote definition id
    get:
      description: |
        Gets vote definition by id
      responses:
        200:
